EasyMarket/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('easyMarketUsers/', include('EasyMarketUsers.urls')),
    path('easyMarketProducts/', include('EasyMarketProducts.urls'))
]

EasyMarketUsers/urls.py
from django.urls import path
from . import views
app_name = "EasyMarketUsers" 

urlpatterns = [
    path('login/', views.login_user, name = 'login'),
    path('logout/', views.logout_user, name = 'logout'),
    path('register/', views.register_user, name = 'register'),
    path('index/', views.index, name = 'index'),
    path("api/etat-caisse/", views.etat_caisse, name="etat_caisse"),
    path("api/check-user/", views.check_user, name="check_user"),
]

EasyMarketUsers/models.py
from datetime import timezone
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.contrib.auth import get_user_model
from decimal import Decimal
from django.conf import settings



class Utilisateurs(AbstractUser):
    nbr_caisse = models.IntegerField(null=True, blank=True)
    statut = models.CharField(max_length= 64)

    def __str__(self):
        return self.username

    class Meta:
        verbose_name = "Utilisateur"
        verbose_name_plural = "Utilisateurs"

class Caisse(models.Model):
    numero = models.CharField(max_length=10)
    etat = models.CharField(max_length=10, default="fermée")  # fermée / ouverte
    montant = models.DecimalField(max_digits=20, decimal_places=2, default=0)

class SessionCaisse(models.Model):
    caisse = models.ForeignKey(Caisse, on_delete=models.SET_NULL, null=True)
    caissier = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    date_ouverture = models.DateTimeField(auto_now_add=True)
    date_fermeture = models.DateTimeField(null=True, blank=True)
    montant_session = models.DecimalField(max_digits=20, decimal_places=2, default=0)
    # montant_final = models.DecimalField(max_digits=10, decimal_places=2, null=True, blank=True)

    def __str__(self):
        return f"Session {self.id} - {self.caisse.numero} ({self.caissier})"

    def ouvrir_session(self):
        self.caisse.etat = "ouverte"
        self.caisse.save()

    def fermer_session(self, montant_final):
        self.date_fermeture = timezone.now()
        self.montant_final = montant_final
        self.save()
        self.caisse.etat = "fermée"
        self.caisse.save()

EasyMarketUsers/forms.py
# from django.contrib.auth.forms import UserCreationForm 
# from django import forms
# from .models import Utilisateurs

# class InscriptionForm(UserCreationForm):
#     statuts = [('admin', "administateur"), ('gestion', "gestionnaire"), ('caisse', "caissier")]
#     statut =  forms.ChoiceField(label = "", choices = statuts)
#     class Meta:
#         model = Utilisateurs
#         fields = ["name", "motDePasse"]

EasyMarketUsers/views.py
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib import messages
from django.shortcuts import render, redirect
from django.http import JsonResponse
from .models import Caisse
from django.contrib.auth.decorators import login_required

User = get_user_model()

def index(request):
    return render(request, "EasyMarketUsers/index.html")

def login_user(request):
    if request.method == "POST":
        username =  request.POST.get("username")
        password = request.POST.get("password") 

        user = authenticate(request, username = username, password = password)
        if user is not None:
            login(request, user)
            # Vérification du rôle
            if user.statut == "gestionnaire":
                return redirect("EasyMarketProducts:dashboard_gestionnaire")  # page gestionnaire
            elif user.statut == "caissier":
                return redirect("EasyMarketProducts:caissier")  # page caissier
            else:
                messages.error(request, "Votre rôle n'est pas reconnu.")
                return redirect("EasyMarketUsers:login")
        else:
            messages.error(request, "Nom d'utilisateur ou mot de passe incorrect")
        
    gestionnaire = User.objects.get(statut = "gestionnaire")
    donnee = {
        "nbre_caisse": gestionnaire.nbr_caisse
    }
    donnee['caisse_range'] = list(range(1, donnee['nbre_caisse'] + 1))

    context = {"donnee":donnee}
    return render(request, "EasyMarketUsers/login.html", context)

def etat_caisse(request):
    numero = request.GET.get("numero")
    if not numero:
        return JsonResponse({"etat": None, "message": ""})

    try:
        caisse = Caisse.objects.get(numero=numero)
        if caisse.etat == "ouverte":
            return JsonResponse({"etat": "occupee", "message": f"La caisse {numero} est déjà occupée"})
        else:
            return JsonResponse({"etat": "libre", "message": f"La caisse {numero} est libre"})
    except Caisse.DoesNotExist:
        return JsonResponse({"etat": "inexistante", "message": f"La caisse {numero} n'existe pas"})
    
def check_user(request):
    numero = request.GET.get("numero")
    code_admin = "123"
    code_gestionnaire = "321"
    code_caissier = "12345"
    if not numero:
        return JsonResponse({"etat": None, "message": "Le code que vous venez d'entrer est invalide"})

    try:
        if numero == code_caissier:
            return JsonResponse({"etat": "", "is_caissier": True})
        elif numero == code_admin:
            return JsonResponse({"etat": "", "is_admin": True})
        elif numero == code_gestionnaire:
            return JsonResponse({"etat": "", "is_gestionnaire": True})
        else:
            return JsonResponse({"etat": "", "is_caissier": False})
    except Caisse.DoesNotExist:
        return JsonResponse({"etat": "inexistante", "message": f"Le numero {numero} n'existe pas"})
    
@login_required
def logout_user(request):
    request.session.flush()  # Effacer la session, y compris scanned_barcodes
    logout(request)
    return redirect("EasyMarketUsers:login") 
    # lorsque tu créera une autre application et tu lui octroira un nom nom tu fera une redirection telle que celle ci     return redirect("nomapplication:index") 
 
    
# def register_user(request):
#     if request.method == "POST":
#         form = InscriptionForm(request.POST)

#         if form.is_valid():
#             form.save()
#             return redirect("mangalib:index")
    
#     else:
#         form = InscriptionForm()

#     return render(request, "EasyMarketUsers/register.html", {"form": form})

def register_user(request):
    code_admin = "123"
    code_gestionnaire = "321"
    code_caissier = "12345"
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        statut = request.POST.get("statut") 
        nbre_caisse = request.POST.get("caisse_numbers", 1)
        code_utilisateur = request.POST.get("token") 

        if statut == "admin":
            if code_utilisateur == code_admin:
                user = User.objects.create_user(username=username, password=password, statut=statut)
                login(request, user)
                return redirect("EasyMarketUsers:index")
            else:
                messages.info(request, "Ce code ne vous appartient pas !")

        elif statut == "gestionnaire":
            if code_utilisateur ==code_gestionnaire:
                user = User.objects.create_user(username=username, password=password, statut=statut, nbr_caisse=nbre_caisse)
                login(request, user)
                return redirect("EasyMarketUsers:index")
            else:
                messages.info(request, "Ce code ne vous appartient pas !")

        elif statut == "caissier":
            if code_utilisateur == code_caissier:
                user = User.objects.create_user(username=username, password=password, statut=statut)
                login(request, user)
                return redirect("EasyMarketUsers:index")
            else:
                messages.info(request, "Ce code ne vous appartient pas !")

    return render(request, "EasyMarketUsers/register.html")

EasyMarketUsers/templates/EasyMarketUsers/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    {% if user.is_authenticated %}
        <p>Connecté sous {{ user.username }} | <a href="{% url 'EasyMarketUsers:logout' %}"> Déconnexion </a></p>
    {% else %}
    <p><a href="{% url 'EasyMarketUsers:login' %}"> Connexion </a></p>
    <p><a href="{% url 'EasyMarketUsers:register' %}"> Inscription </a></p>
    {% endif %}
</body>
</html>

EasyMarketUsers/templates/EasyMarketUsers/login.html
{% load static %}

<html lang="fr">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Connectez vous à votre compte</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  
  <link rel="stylesheet" href="{% static 'EasyMarketUsers/css/style.css' %}">

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

</head>

<body>

  <main>
    <div class="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

              <!-- <div class="d-flex justify-content-center py-4">
                <a href="index.html" class="logo d-flex align-items-center w-auto">
                  <img src="assets/img/logo.png" alt="">
                  <span class="d-none d-lg-block">NiceAdmin</span>
                </a>
              </div>End Logo -->

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Connectez vous</h5>
                    <p class="text-center small">Entrez vos informations personnelles pour vous connecter à votre compte</p>
                  </div>
                  <form class="row g-3 needs-validation" method="post">
                    {% csrf_token %}
                    {% if messages %}
                    {% for message in messages %}
                        <div class="alert alert-danger alert-dismissible fade show" role="alert">
                            {{ message }}
                            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                        </div>
                    {% endfor %}
                    {% endif %}
                    <div class="col-12">
                      <label for="yourName" class="form-label">Nom d'utilisateur</label>
                      <input type="text" name="username" class="form-control" id="yourName" required>
                      <div class="invalid-feedback">Please, enter your name!</div>
                    </div>

                    <div class="col-12">
                      <label for="yourCode" class="form-label">Code utilisateur</label>
                      <input type="text" name="yourCode" class="form-control" id="yourCode" required>
                    </div>
                    
                    <div class="col-12" style="display: none;" id="choose_caisse">
                      <label for="caisse_select">Choisissez votre caisse :</label>
                      <select class="form-select" name="caisse_select" id="caisse_select">
                        <option value="">-- Sélectionner --</option>
                        {% if donnee.caisse_range %}
                          {% for i in donnee.caisse_range %}
                            <option value="{{ i }}">Caisse N°{{ i }}</option>
                              {% endfor %}
                          {% endif %}
                          </select>
                    </div>

                    <div id="etat_caisse_message" style="margin-top:5px;font-weight:bold;"></div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Mot de passe</label>
                      <input type="password" name="password" class="form-control" id="yourPassword" required>
                      <div class="invalid-feedback">Please enter your password!</div>
                    </div>

                    <div class="col-12">
                      <button class="btn btn-primary w-100" type="submit">Se connecter</button>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0">Vous n'avez pas de compte? <a href="{% url 'EasyMarketUsers:register' %}">Créer un compte</a></p>
                    </div>
                  </form>

                </div>
            </div>

            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


  <!-- <script src="assets/js/main.js"></script> -->
   <script>
      document.getElementById("caisse_select").addEventListener("change", function() {
          const numero = this.value;
          const messageDiv = document.getElementById("etat_caisse_message");
      
          if (!numero) {
              messageDiv.textContent = "";
              return;
          }
        
          fetch(`/easyMarketUsers/api/etat-caisse/?numero=${numero}`)
              .then(response => response.json())
              .then(data => {
                  messageDiv.textContent = data.message;
                  messageDiv.style.color = data.etat === "occupee" ? "red" :
                                           data.etat === "libre" ? "green" : "orange";
              });
      });

      $(document).ready(function() {
            $('#yourCode').on('change', function() {
                const selectedValue = $(this).val();

            fetch(`/easyMarketUsers/api/check-user/?numero=${selectedValue}`)
              .then(response => response.json())
              .then(data => {
                if (data.is_caissier) {
                    $('#choose_caisse').show();
                    $('#caisse_select').attr('required', true);
                } else {
                    $('#choose_caisse').hide();
                    $('#caisse_select').attr('required', false);
                }
              });

            });
      });
  </script>

</body>

</html>

EasyMarketUsers/templates/EasyMarketUsers/register.html
{% load static %}
<html lang="fr">

<head>
  <meta charset="utf-8">
  <meta content="width=device-width, initial-scale=1.0" name="viewport">

  <title>Création de compte</title>
  <meta content="" name="description">
  <meta content="" name="keywords">

  <!-- Google Fonts -->
  <link href="https://fonts.gstatic.com" rel="preconnect">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,600,600i,700,700i|Nunito:300,300i,400,400i,600,600i,700,700i|Poppins:300,300i,400,400i,500,500i,600,600i,700,700i" rel="stylesheet">
  
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
  <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.11.3/font/bootstrap-icons.min.css">
  
  <link rel="stylesheet" href="{% static 'EasyMarketUsers/css/style.css' %}">

  <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>


</head>

<body>

  <main>

    <div class="container">

      <section class="section register min-vh-100 d-flex flex-column align-items-center justify-content-center py-4">
        <div class="container">
          <div class="row justify-content-center">
            <div class="col-lg-4 col-md-6 d-flex flex-column align-items-center justify-content-center">

              <!-- <div class="d-flex justify-content-center py-4">
                <a href="index.html" class="logo d-flex align-items-center w-auto">
                  <img src="assets/img/logo.png" alt="">
                  <span class="d-none d-lg-block">NiceAdmin</span>
                </a>
              </div>End Logo -->

              <div class="card mb-3">

                <div class="card-body">

                  <div class="pt-4 pb-2">
                    <h5 class="card-title text-center pb-0 fs-4">Créer un compte</h5>
                    <p class="text-center small">Entrez vos informations personnelles pour créer un compte</p>
                  </div>

                  <form class="row g-3 needs-validation" method="post">
                    {% csrf_token %}
                    <div class="col-12">
                      <label for="yourName" class="form-label">Nom d'utilisateur</label>
                      <input type="text" name="username" class="form-control" id="yourName" required>
                      <div class="invalid-feedback">Please, enter your name!</div>
                    </div>

                    <div class="col-12">
                        <select class="form-select" name="statut" id="statut" required>
                            <option selected>Quel est votre statut</option>
                            <option value="admin">Admin</option>
                            <option value="gestionnaire">Gestionnaire</option>
                            <option value="caissier">Caissier</option>
                          </select>
                    </div>
                    
                    <div id="nb_caisse" class="mb-3" style="display: none;">
                      <label for="card_number" class="form-label">Nombre de caisse</label>
                      <input type="number" name="caisse_numbers" id="caisse_numbers" class="form-control" placeholder="1 ou 2 ou 3 et cetera">
                    </div>

                    <div class="col-12">
                        <label for="token" class="form-label">Entrez votre code</label>
                        <input type="text" name="token" class="form-control" id="token" required>
                        <!-- <div class="invalid-feedback">Please, enter your name!</div> -->
                         {% for message in messages %}
                            <div style="color: red;">{{ message }}</div>
                         {% endfor %}
                    </div>

                    <div class="col-12">
                      <label for="yourPassword" class="form-label">Mot de passe</label>
                      <input type="password" name="password" class="form-control" id="yourPassword" required>
                      <div class="invalid-feedback">Please enter your password!</div>
                    </div>

                    <div class="col-12">
                      <div class="form-check">
                        <input class="form-check-input" name="terms" type="checkbox" value="" id="acceptTerms" required>
                        <label class="form-check-label" for="acceptTerms">J'accepte les <a href="#">termes et conditions d'utilisation</a></label>
                        <div class="invalid-feedback">You must agree before submitting.</div>
                      </div>
                    </div>
                    <div class="col-12">
                      <button class="btn btn-primary w-100" type="submit">Créer mon compte</button>
                    </div>
                    <div class="col-12">
                      <p class="small mb-0">Vous avez déjà un compte? <a href="{% url 'EasyMarketUsers:login' %}">Connectez vous</a></p>
                    </div>
                  </form>

                </div>
            </div>

            </div>
          </div>
        </div>

      </section>

    </div>
  </main><!-- End #main -->

  <a href="#" class="back-to-top d-flex align-items-center justify-content-center"><i class="bi bi-arrow-up-short"></i></a>


  <!-- <script src="assets/js/main.js"></script> -->
  <script>
        $(document).ready(function() {
            $('#statut').on('change', function() {
                const selectedValue = $(this).val();
                if (selectedValue === 'gestionnaire') {
                    $('#nb_caisse').show();
                } else {
                    $('#nb_caisse').hide();
                }
            });
        });
  </script>

</body>

</html>